#define ST(A) #A
#define STR(A) ST(A)

#ifndef DEF_ESP_RDCD_SETUP
#define DEF_ESP_RDCD_SETUP

#define WIFI_SSID STR(ESP_RDCD_WIFI_SSID)
#define WIFI_PWD  STR(ESP_RDCD_WIFI_PWD)

#define MQTT_CLIENT_ID STR(ESP_RDCD_MQTT_CLIENT_ID)
#define MQTT_SERVER    STR(ESP_RDCD_MQTT_SERVER)
#define MQTT_USERNAME  STR(ESP_RDCD_MQTT_USERNAME)
#define MQTT_PASSWORD  STR(ESP_RDCD_MQTT_PWD)
#define MQTT_PORT      ESP_RDCD_MQTT_PORT

#define HOSTNAME      STR(ESP_RDCD_HOSTNAME)
#define PIN_PWM       ESP_RDCD_PIN_PWM
#define FREQUENCY     ESP_RDCD_FREQUENCY
#define MAX_MSG_SIZE  ESP_RDCD_MAX_MSG_SIZE

#endif